### ISSUE TITLE
Mobile dropdown won't open on mobile after scrolling

### ISSUE THREAD

**Issue by Nicolas-Connor** [EricKulchycki/WeedApp#83]
When viewing a page on mobile, if you open the drobdown, then scroll down the page without first closing the dropdown.  The dropdown will automatically close as expected, but won't re-open next time you click on the hamburger.

![video of broken dropdown](https://user-images.githubusercontent.com/8783674/71337614-0adb3a80-2512-11ea-95dd-698525559c15.gif)

**Comment by EricKulchycki** [comment]
Oh damn never even noticed that, thanks.
